# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16TLMxcyXv6fv3-BVuxYU-pycxoBdIfB_
"""

import cv2
import numpy as np
from google.colab import files
from matplotlib import pyplot as plt

# ====== Constants ======
H_real = 2.0     # Real door height in meters
focal_length = 1700  # Virtual focal length in pixels

# ====== Upload images ======
print("Upload images of the door:")
uploaded = files.upload()
image_paths = list(uploaded.keys())

distances = []

def estimate_distance(img, title=None):
    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Edge detection
    edges = cv2.Canny(gray, 50, 150)

    # Find contours (closed shapes)
    contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    max_h = 0
    best = None

    # Find the tallest contour (assumed to be the door)
    for c in contours:
        x, y, w, h = cv2.boundingRect(c)
        if h > max_h and h > 100 and w>110:  # filter small objects
            max_h = h
            best = (x, y, w, h)

    if best is None:
        print("Door not detected")
        return None, None

    x, y, w, h = best

    # Perspective distance formula
    distance = (H_real * focal_length) / h

    # Convert edges to color so we can draw a red rectangle
    edges_color = cv2.cvtColor(edges, cv2.COLOR_GRAY2BGR)
    cv2.rectangle(edges_color, (x, y), (x+w, y+h), (0, 0, 255),5)

    # Display result
    plt.figure(figsize=(8,5))
    if title is None:
        plt.title(f"Estimated distance: {distance:.2f} meters")
    else:
        plt.title(title)
    plt.imshow(edges_color)
    plt.axis('off')
    plt.show()

    print("Door height in pixels:", h)
    return distance, edges_color

# ====== Process all images ======
first_vis = None

for i, path in enumerate(image_paths):
    img = cv2.imread(path)
    d, vis = estimate_distance(img)
    if d is not None:
        distances.append(d)
        print("Distance:", d, "meters\n")

# ====== Average distance and calibration display ======
if len(distances) > 0:
    avg_distance = sum(distances) / len(distances)
    print("Average distance from all images:", avg_distance, "meters")

    plt.figure(figsize=(8,5))
    plt.axis('off')
    plt.show()

